<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework><Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>CS8618</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Astrodaiva.Api/Astrodaiva.Api.csproj" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
    <Compile Include="../Integration/*.cs" Link="Integration/%(Filename)%(Extension)" />
    <Compile Include="../Data/Models/*.cs" Link="Models/%(Filename)%(Extension)" />
    <Compile Include="../Data/Enum/*.cs" Link="Enums/%(Filename)%(Extension)" />
    <Content Update="Fixtures/*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
