// <auto-generated />
using System;
using Astrodaiva.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Astrodaiva.Api.Migrations
{
    [DbContext(typeof(AstroDbContext))]
    partial class AstroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Astrodaiva.Api.Data.AppDbSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AppDbJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("appdb_snapshots");
                });

            modelBuilder.Entity("Astrodaiva.Api.Data.AstroEventPlanetRow", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Planet")
                        .HasColumnType("int");

                    b.Property<bool>("IsRetrograde")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsZodiacTransitioning")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NewZodiacSign")
                        .HasColumnType("int");

                    b.Property<int>("PreviousZodiacSign")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransitionTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Date", "Planet");

                    b.ToTable("astro_event_planets");
                });

            modelBuilder.Entity("Astrodaiva.Api.Data.AstroEventRow", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Barber")
                        .HasColumnType("int");

                    b.Property<int>("Beauty")
                        .HasColumnType("int");

                    b.Property<int>("BuyStuff")
                        .HasColumnType("int");

                    b.Property<int>("Contracts")
                        .HasColumnType("int");

                    b.Property<string>("EventText")
                        .HasColumnType("longtext");

                    b.Property<int>("Gardening")
                        .HasColumnType("int");

                    b.Property<int>("ImportantTasks")
                        .HasColumnType("int");

                    b.Property<int>("Love")
                        .HasColumnType("int");

                    b.Property<int>("Meetings")
                        .HasColumnType("int");

                    b.Property<bool>("MoonDayIsTriple")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MoonDayMiddle")
                        .HasColumnType("int");

                    b.Property<DateTime>("MoonDayMiddleTransitionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MoonDayNew")
                        .HasColumnType("int");

                    b.Property<int>("MoonDayPrevious")
                        .HasColumnType("int");

                    b.Property<DateTime>("MoonDayTransitionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MoonEclipse")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MoonPhase")
                        .HasColumnType("int");

                    b.Property<int>("NewIdeas")
                        .HasColumnType("int");

                    b.Property<bool>("SunEclipse")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Tech")
                        .HasColumnType("int");

                    b.Property<int>("Travel")
                        .HasColumnType("int");

                    b.HasKey("Date");

                    b.ToTable("astro_events");
                });

            modelBuilder.Entity("Astrodaiva.Api.Data.AstroPlanetEventRow", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Planet1")
                        .HasColumnType("int");

                    b.Property<int>("Planet2")
                        .HasColumnType("int");

                    b.Property<int>("AspectSymbol")
                        .HasColumnType("int");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.HasKey("Date", "Planet1", "Planet2", "AspectSymbol");

                    b.HasIndex("Date");

                    b.ToTable("astro_planet_events");
                });

            modelBuilder.Entity("Astrodaiva.Api.Data.MoonDayDetailsRow", b =>
                {
                    b.Property<int>("MoonDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("MoonDayInfo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MoonDay");

                    b.ToTable("moon_day_details");
                });

            modelBuilder.Entity("Astrodaiva.Api.Data.PlanetInRetrogradeDetailsRow", b =>
                {
                    b.Property<int>("PlanetInRetrograde")
                        .HasColumnType("int");

                    b.Property<string>("PlanetInRetrogradeInfo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PlanetInRetrograde");

                    b.ToTable("planet_in_retrograde_details");
                });

            modelBuilder.Entity("Astrodaiva.Api.Data.PlanetInZodiacDetailsRow", b =>
                {
                    b.Property<int>("Planet")
                        .HasColumnType("int");

                    b.Property<int>("ZodiacSign")
                        .HasColumnType("int");

                    b.Property<string>("PlanetInZodiacInfo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Planet", "ZodiacSign");

                    b.ToTable("planet_in_zodiac_details");
                });

            modelBuilder.Entity("Astrodaiva.Api.Data.AstroEventPlanetRow", b =>
                {
                    b.HasOne("Astrodaiva.Api.Data.AstroEventRow", null)
                        .WithMany()
                        .HasForeignKey("Date")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Astrodaiva.Api.Data.AstroPlanetEventRow", b =>
                {
                    b.HasOne("Astrodaiva.Api.Data.AstroEventRow", null)
                        .WithMany()
                        .HasForeignKey("Date")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
